### ISSUE TITLE
`TypeError: (0 , w.createStyles) is not a function` when adding `<ContextMenuProvider> ` in _app.tsx.

### ISSUE THREAD

**Issue by liaodalin19903** [icflorescu/mantine-contextmenu#70]
**Describe the bug**
in my next.js with electron template project:

when I add `<MantineProvider>` in _app.tsx, it works fine.
```
// _app.tsx
...
function MyApp({ Component, pageProps }: AppProps) {
  return (
    <MantineProvider>
        <React.Fragment>
          <MyLayout>
              <Component {...pageProps} />
          </MyLayout>
        </React.Fragment>
    </MantineProvider>   
  );
}
```

but when I add <ContextMenuProvider> it get error:

```
<MantineProvider>
  <ContextMenuProvider> 
    <React.Fragment>
      <MyLayout>
          <Component {...pageProps} />
      </MyLayout>
    </React.Fragment>
  </ContextMenuProvider>
</MantineProvider>   
```

the error info:
```
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
 ⨯ TypeError: (0 , w.createStyles) is not a function
    at Object.<anonymous> (/Users/john/Desktop/projects/test/mycode-layout-demo-01/node_modules/.pnpm/registry.npmmirror.com+mantine-contextmenu@1.3.15_@mantine+core@7.0.0_@mantine+hooks@7.0.0_react@18.2.0/node_modules/mantine-contextmenu/dist/index.cjs:1:944)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at mod.require (/Users/john/Desktop/projects/test/mycode-layout-demo-01/node_modules/.pnpm/registry.npmmirror.com+next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:110:18)
    at mantine-contextmenu (/Users/john/Desktop/projects/test/mycode-layout-demo-01/renderer/.next/server/pages/_app.js:442:18)
    at __webpack_require__ (/Users/john/Desktop/projects/test/mycode-layout-demo-01/renderer/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.tsx:17:77)
    at __webpack_require__.a (/Users/john/Desktop/projects/test/mycode-layout-demo-01/renderer/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/_app.tsx:1:21)
    at ./pages/_app.tsx (/Users/john/Desktop/projects/test/mycode-layout-demo-01/renderer/.next/server/pages/_app.js:289:1) {
  page: '/'
}
 ✓ Compiled /_error in 302ms (1412 modules)
TypeError: (0 , w.createStyles) is not a function
    at Object.<anonymous> (/Users/john/Desktop/projects/test/mycode-layout-demo-01/node_modules/.pnpm/registry.npmmirror.com+mantine-contextmenu@1.3.15_@mantine+core@7.0.0_@mantine+hooks@7.0.0_react@18.2.0/node_modules/mantine-contextmenu/dist/index.cjs:1:944)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at mod.require (/Users/john/Desktop/projects/test/mycode-layout-demo-01/node_modules/.pnpm/registry.npmmirror.com+next@13.5.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:110:18)
    at mantine-contextmenu (/Users/john/Desktop/projects/test/mycode-layout-demo-01/renderer/.next/server/pages/_app.js:442:18)
    at __webpack_require__ (/Users/john/Desktop/projects/test/mycode-layout-demo-01/renderer/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.tsx:17:77)
    at __webpack_require__.a (/Users/john/Desktop/projects/test/mycode-layout-demo-01/renderer/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/_app.tsx:1:21)
    at ./pages/_app.tsx (/Users/john/Desktop/projects/test/mycode-layout-demo-01/renderer/.next/server/pages/_app.js:289:1)
```

**Screenshots**

![image](https://github.com/icflorescu/mantine-contextmenu/assets/12727582/81a2eec6-abb0-4ed7-b531-da98b8019f47)

- OS: macOS 
---

I have tried remove `.next/` and rebuild, it still not work.

**Comment by icflorescu** [comment]
That happens because mantine-contextmenu is not **yet** compatible with Mantine 7.x, which introduced [breaking changes regarding styling](https://mantine.dev/changelog/7-0-0/).

I'll hopefully be able to come up with an updated version over the next couple of weeks.

While this is one of my dearest open-source projects and has quite a lot of users, I lack [proper sponsorship](https://github.com/sponsors/icflorescu) to be able to dedicate the necessary time resources to it, but **it certainly is** on my to-do list for the near future.
